# fly.toml app configuration file generated for nyefan-coturn on 2025-06-15T21:06:02-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nyefan-coturn'
primary_region = 'ord'
kill_signal = 'SIGTERM'
kill_timeout = '2m0s'

[build]
  image = 'docker.io/coturn/coturn:alpine'

[experimental]
cmd = [
  '--external-ip="$(detect-external-ip)"',
  '--listening-ip="0.0.0.0"',
  '--listening-ip="fly-global-services"',
  '--relay-ip="fly-global-services"',
  '--realm="matrix.nyefan.org"',
  '--use-auth-secret',
  '--static-auth-secret="${TUWUNEL_TURN_SECRET}"',
]

[deploy]
  strategy = 'rolling'
  max_unavailable = 1.0
  wait_timeout = '10m0s'

[[services]]
  protocol = 'tcp'
  internal_port = 3478
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 3478

  [[services.ports]]
    port = 5349
    handlers = ['tls']

[[services]]
  protocol = 'udp'
  internal_port = 3478
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 3478

  [[services.ports]]
    port = 5349
    handlers = ['tls']

#[[services]]
#  protocol = 'udp'
#  internal_port = 0
#  auto_stop_machines = "suspend"
#  auto_start_machines = true
#  min_machines_running = 0
#
#  [[services.ports]]
#    start_port = 49152
#    end_port = 65535

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
